
services:
  # api:
  #   container_name: dotnet_api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${API_PORT}:80"
  #   depends_on:
  #     - sqlserver
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};
  #   networks:
  #     - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "${DB_PORT}:1433"
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

  sqlcmd-client:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd-client
    entrypoint: ["tail", "-f", "/dev/null"]  # Keeps the container alive
    environment:
      - SQLSERVER=sqlserver
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - backend
    depends_on:
      - sqlserver

networks:
  backend:

volumes:
  sql_data:
